### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by l0oky** [evantahler/ah-resque-ui#8]
Running an actionhero server ( with fakeredis enabled ) and visiting `http://127.0.0.1:8080/resque` produces the following error, resulting in a server crash: 

```bash
2016-07-25T17:12:47.211Z - notice: *** Server Started ***
/home/l0oky/Projects/nodejs/src/myproject/node_modules/ah-resque-ui/actions/ah-resque-ui.js:16
    data.response.packageDetails.redis = api.config.redis.client.args;
                                                                ^

TypeError: Cannot read property 'args' of undefined
    at Object.exports.packageDetails.run (/home/l0oky/Projects/nodejs/src/myproject/node_modules/ah-resque-ui/actions/ah-resque-ui.js:16:65)
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/actionhero/initializers/actionProcessor.js:264:31
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:726:13
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:52:16
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:269:32
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:44:16
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:723:17
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:167:37
    at Object.middleware.ah-resque-ui-proxy-middleware.preProcessor (/home/l0oky/Projects/nodejs/src/myproject/node_modules/ah-resque-ui/initializers/ah-resque-ui.js:33:18)
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/actionhero/initializers/actionProcessor.js:144:72
    at /home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/home/l0oky/Projects/nodejs/src/myproject/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by evantahler** [comment]
What version of Actionhero? V14+ is required

**Comment by l0oky** [comment]
I use actionhero version 14.0.9
